language: java
install: ant download-dependencies
script: ant ci

branches:
  except:
    - /dev-build-.*/

after_deploy:
  |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      echo -e "Publishing javadoc...\n"

      cp -R dist/javadoc $HOME/javadoc-latest

      cd $HOME
      git config --global user.email "travis@travis-ci.org"
      git config --global user.name "travis-ci"
      git clone --quiet --branch=gh-pages https://${AUTH_TOKEN}@github.com/Codisimus/Shortcuts gh-pages > /dev/null

      cd gh-pages
      git rm -rf ./javadoc
      cp -Rf $HOME/javadoc-latest ./javadoc
      git add -f .
      git commit -m "Latest javadoc on successful travis build $TRAVIS_BUILD_NUMBER auto-pushed to gh-pages"
      git push -fq origin gh-pages > /dev/null

      echo -e "Published Javadoc to gh-pages.\n"
    fi

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=dev-build-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER on $(date -u "+%Y-%m-%d-%H-%M-%S")"
  - git push --quiet https://$AUTH_TOKEN@github.com/Codisimus/Shortcuts $GIT_TAG

deploy:
  - provider: releases
    prerelease: true
    api_key: $AUTH_TOKEN
    file: "dist/Shortcuts.jar"
    skip_cleanup: true
    on:
      branch: master
      tags: false
  - provider: releases
    prerelease: false
    api_key: $AUTH_TOKEN
    file: "dist/Shortcuts.jar"
    skip_cleanup: true
    on:
      tags: true
