name: Shortcuts
main: com.codisimus.plugins.shortcuts.Shortcuts
version: 0.1.0
author: Codisimus
website: www.codisimus.com
description: Shortcuts to executing console commands
commands:
  w:
    description: Sends a private message to the specified Player
    usage: /w [Player] [Message]
    permission: shortcuts.w
    permission-message: You do not have permission to do that
  re:
    description: Replies to your last private message
    usage: /re [Message]
    permission: shortcuts.re
    permission-message: You do not have permission to do that
  td:
    description: Toggles downfall for current World
    usage: /td
    permission: shortcuts.td
    permission-message: You do not have permission to do that
  day:
    description: Sets time of current World to 0
    usage: /day
    permission: shortcuts.day
    permission-message: You do not have permission to do that
  night:
    description: Sets time of current World to 18000
    usage: /night
    permission: shortcuts.night
    permission-message: You do not have permission to do that
  gm:
    description: Toggles gamemode of specified Player
    usage: /gm (Player)
    permission: shortcuts.gm
    permission-message: You do not have permission to do that
  tp:
    description: Teleports the specified Player to another Player
    usage: /tp (PlayerToTele) [DestinationPlayer]
    permission: shortcuts.tp
    permission-message: You do not have permission to do that
  tph:
    description: Teleports the specified Player to you
    usage: /tph [PlayerToTele]
    permission: shortcuts.tph
    permission-message: You do not have permission to do that
  spy:
    description: Opens another Players Inventory
    usage: /spy [Player]
    permission: shortcuts.spy
    permission-message: You do not have permission to do that
permissions:
  shortcuts.w:
    default: true
  shortcuts.re:
    default: true
  shortcuts.td:
    default: op
  shortcuts.day:
    default: op
  shortcuts.night:
    default: op
  shortcuts.gm:
    default: op
  shortcuts.tp:
    default: op
  shortcuts.tph:
    default: op
  shortcuts.spy:
    default: op