name: Shortcuts
main: com.codisimus.plugins.shortcuts.Shortcuts
version: 0.2.0
author: Codisimus
website: www.codisimus.com
description: Shortcuts to executing console commands
commands:
  prl:
    description: Reloads a specified plugin
    usage: /prl <plugin>
    permission: shortcuts.plr
    permission-message: You do not have permission to do that
  enable:
    description: Enables a specified plugin
    usage: /enable <plugin>
    permission: shortcuts.enable
    permission-message: You do not have permission to do that
  disable:
    description: Disables a specified plugin
    usage: /enable <plugin>
    permission: shortcuts.disable
    permission-message: You do not have permission to do that
  spawn:
    description: Teleports you to the server spawn
    usage: /spawn
    permission: shortcuts.spawn
    permission-message: You do not have permission to do that
  w:
    description: Sends a private message to the specified Player
    usage: /w [Player] [Message]
    permission: shortcuts.w
    permission-message: You do not have permission to do that
  re:
    description: Replies to your last private message
    usage: /re [Message]
    permission: shortcuts.re
    permission-message: You do not have permission to do that
  td:
    description: Toggles downfall for current World
    usage: /td
    permission: shortcuts.td
    permission-message: You do not have permission to do that
  day:
    description: Sets time of current World to 0
    usage: /day
    permission: shortcuts.day
    permission-message: You do not have permission to do that
  night:
    description: Sets time of current World to 18000
    usage: /night
    permission: shortcuts.night
    permission-message: You do not have permission to do that
  gm:
    description: Toggles gamemode of specified Player
    usage: /gm (Player)
    permission: shortcuts.gm
    permission-message: You do not have permission to do that
  tp:
    description: Teleports the specified Player to another Player
    usage: /tp (PlayerToTele) [DestinationPlayer]
    permission: shortcuts.tp
    permission-message: You do not have permission to do that
  tph:
    description: Teleports the specified Player to you
    usage: /tph [PlayerToTele]
    permission: shortcuts.tph
    permission-message: You do not have permission to do that
  spy:
    description: Opens another Players Inventory
    usage: /spy [Player]
    permission: shortcuts.spy
    permission-message: You do not have permission to do that
  ban:
    description: Temporarily bans the specified Player
    usage: /ban [Player] [Time] [Reason]
    permission: shortcuts.ban
    permission-message: You do not have permission to do that
  setspawn:
    description: Changes the Server spawn to your current location
    usage: /setspawn
    permission: shortcuts.setspawn
    permission-message: You do not have permission to do that
  fly:
    description: Allows you to fly at high speeds even while in survival mode
    usage: /fly
    permission: shortcuts.fly
    permission-message: You do not have permission to do that
permissions:
  shortcuts.prl:
    default: op
  shortcuts.enable:
    default: op
  shortcuts.disable:
    default: op
  shortcuts.spawn:
    default: true
  shortcuts.w:
    default: true
  shortcuts.re:
    default: true
  shortcuts.td:
    default: op
  shortcuts.day:
    default: op
  shortcuts.night:
    default: op
  shortcuts.gm:
    default: op
  shortcuts.tp:
    default: op
  shortcuts.tph:
    default: op
  shortcuts.spy:
    default: op
  shortcuts.ban:
    default: op
  shortcuts.setspawn:
    default: op
  shortcuts.fly:
    default: op